- name: "XFCE4-Desktop"
  description: "XFCE4 - lightweight desktop fast and low on system resources, visually appealing and user friendly."
  hidden: false
  selected: false
  expanded: false
  critical: true
  subgroups:
      - name: "EndeavourOS-theming"
        description: "EndeavourOS XFCE4 theming (unselect to install vanilla)"
        selected: false
        packages:
            - arc-gtk-theme-eos
            - eos-lightdm-slick-theme
            - eos-qogir-icons
            - endeavouros-skel-xfce4
            - endeavouros-xfce4-terminal-colors
      - name: "XFCE4-Desktop"
        description: "XFCE4 needed packages"
        selected: false
        packages:
         - file-roller
         - galculator
         - gvfs
         - gvfs-afc
         - gvfs-gphoto2
         - gvfs-mtp
         - gvfs-nfs
         - gvfs-smb
         - lightdm
         - lightdm-slick-greeter
         - network-manager-applet
         - parole
         - ristretto
         - thunar-archive-plugin
         - thunar-media-tags-plugin
         - xdg-user-dirs-gtk
         - xed
         - xfce4
         - xfce4-battery-plugin
         - xfce4-datetime-plugin
         - xfce4-mount-plugin
         - xfce4-netload-plugin
         - xfce4-notifyd
         - xfce4-pulseaudio-plugin
         - xfce4-screensaver
         - xfce4-screenshooter
         - xfce4-taskmanager
         - xfce4-wavelan-plugin
         - xfce4-weather-plugin
         - xfce4-whiskermenu-plugin
         - xfce4-xkb-plugin
- name: "i3-Window-Manager"
  description: "i3 tiling window manager, primarily targeted at developers and advanced users."
  hidden: false
  selected: false
  expanded: false
  critical: true
  packages:
    - acpi
    - arandr
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - endeavouros-skel-i3wm
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - awesome-terminal-fonts
    - dex
    - dmenu
    - dunst
    - endeavouros-xfce4-terminal-colors
    - file-roller
    - galculator
    - gthumb
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - i3blocks
    - i3-gaps
    - i3lock
    - i3status
    - jq
    - lightdm
    - lightdm-slick-greeter
    - lxappearance-gtk3
    - mpv
    - network-manager-applet
    - nitrogen
    - numlockx
    - picom
    - playerctl
    - polkit-gnome
    - rofi
    - scrot
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - tumbler
    - xbindkeys
    - xdg-user-dirs-gtk
    - xed
    - xfce4-terminal
    - xorg-xbacklight
    - xorg-xdpyinfo
- name: "KDE-Desktop"
  description: "KDE-Plasma Desktop - Simple by default, powerful when needed."
  hidden: false
  selected: false
  critical: true
  packages:
    - ark
    - audiocd-kio
    - breeze-gtk
    - dolphin
    - dragon
    - elisa
    - eos-plasma-sddm-config
    - gwenview
    - kcalc
    - kate
    - kdeconnect
    - kde-gtk-config
    - khotkeys
    - kinfocenter
    - kinit
    - kio-fuse
    - konsole
    - kscreen
    - kwallet-pam
    - okular
    - plasma-desktop
    - plasma-disks
    - plasma-nm
    - plasma-pa
    - powerdevil
    - print-manager
    - sddm-kcm
    - solid
    - spectacle
    - xsettingsd
- name: "GNOME-Desktop"
  description: "GNOME Desktop - designed to put you in control and get things done."
  hidden: false
  selected: false
  critical: true
  packages:
    - adwaita-icon-theme
    - arc-gtk-theme-eos
    - eos-qogir-icons
    - eog
    - evince
    - file-roller
    - gdm
    - gedit
    - gnome-calculator
    - gnome-control-center
    - gnome-disk-utility
    - gnome-keyring
    - gnome-nettool
    - gnome-power-manager
    - gnome-screenshot
    - gnome-shell
    - gnome-terminal
    - gnome-themes-extra
    - gnome-tweaks
    - gnome-usage
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - nautilus
    - nautilus-sendto
    - sushi
    - totem
    - xdg-user-dirs-gtk
- name: "MATE-Desktop"
  description: "MATE Desktop - the continuation of GNOME 2"
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - celluloid
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - mate
    - mate-extra
    - network-manager-applet
    - xdg-user-dirs-gtk
- name: "Cinnamon-Desktop"
  description: "Cinnamon Desktop - advanced innovative features and a traditional user experience."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - celluloid
    - cinnamon
    - cinnamon-translations
    - file-roller
    - gnome-calculator
    - gnome-screenshot
    - gnome-system-monitor
    - gnome-terminal
    - gthumb
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - nemo-fileroller
    - nemo-image-converter
    - nemo-preview
    - nemo-share
    - x-apps
    - xdg-user-dirs-gtk
- name: "Budgie-Desktop"
  description: "Budgie - I Tawt I Taw A Purdy Desktop"
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - budgie-desktop
    - budgie-desktop-view
    - budgie-extras
    - budgie-screensaver
    - eog
    - evince
    - file-roller
    - gedit
    - gnome-control-center
    - gnome-disk-utility
    - gnome-keyring
    - gnome-nettool
    - gnome-power-manager
    - gnome-terminal
    - gnome-themes-extra
    - gnome-usage
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - nautilus
    - nautilus-sendto
    - network-manager-applet
    - sushi
    - totem
    - xdg-user-dirs-gtk
- name: "LXQT-Desktop"
  description: "The Lightweight Qt Desktop Environment."
  hidden: false
  selected: false
  critical: true
  packages:
    - audiocd-kio
    - baka-mplayer
    - breeze
    - breeze-gtk
    - eos-sddm-theme
    - featherpad
    - gvfs
    - gvfs-mtp
    - kio-fuse
    - libstatgrab
    - libsysstat
    - lm_sensors
    - lxqt
    - lxqt-archiver
    - network-manager-applet
    - oxygen-icons
    - pavucontrol-qt
    - print-manager
    - qt5-translations
    - xdg-utils
    - xscreensaver
    - xsettingsd
- name: "LXDE-Desktop"
  description: "The Lightweight Desktop Environment."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-lxdm-gtk3
    - eos-qogir-icons
    - celluloid
    - file-roller
    - galculator
    - gnome-screenshot
    - gpicview
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lxappearance-gtk3
    - obconf
    - lxde-common
    - lxde-icon-theme
    - lxhotkey-gtk3
    - lxinput-gtk3
    - lxlauncher-gtk3
    - lxpanel-gtk3
    - lxrandr-gtk3
    - lxsession-gtk3
    - lxtask-gtk3
    - lxterminal
    - openbox
    - pcmanfm-gtk3
    - lxmusic
    - network-manager-applet
    - xdg-user-dirs-gtk
    - xed

- name: "BSPWM Edition"
  description: "BSPWM Community Edition."
  hidden: false
  selected: false
  critical: true
  packages:
    - acpi
    - arandr
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - bspwm
    - dex
    - dunst
    - endeavouros-xfce4-terminal-colors
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - eos-skel-ce-bspwm
    - feh
    - file-roller
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - htop
    - i3lock
    - jq
    - lightdm
    - lightdm-slick-greeter
    - lxappearance-gtk3
    - mpv
    - network-manager-applet
    - nitrogen
    - picom
    - polkit-gnome
    - polybar
    - rofi
    - scrot
    - sxhkd
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
    - thunar-volman
    - ttf-nerd-fonts-symbols
    - tumbler
    - xbindkeys
    - xclip
    - xcursor-neutral
    - xdg-user-dirs-gtk
    - xed
    - xfce4-terminal
    - xorg-xbacklight
    - xorg-xdpyinfo
    - xorg-xsetroot

- name: "Openbox Edition"
  description: "Openbox Community Edition."
  hidden: false
  selected: false
  critical: true
  packages:
    - acpi
    - arandr
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - dex
    - dmenu
    - dunst
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - eos-skel-ce-openbox
    - feh
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - jgmenu
    - jq
    - lightdm
    - lightdm-slick-greeter
    - lxappearance-gtk3
    - mpv
    - network-manager-applet
    - nitrogen
    - obconf
    - openbox
    - pasystray
    - picom
    - polkit-gnome
    - rofi
    - scrot
    - slock
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
    - thunar-volman
    - tint2
    - ttf-nerd-fonts-symbols
    - tumbler
    - xbindkeys
    - xcursor-neutral
    - xdg-user-dirs-gtk
    - xed
    - xfce4-terminal
    - xorg-xbacklight
    - xorg-xdpyinfo

- name: "Qtile Edition"
  description: "Qtile Community Edition."
  hidden: false
  selected: false
  critical: true
  packages:
    - acpi
    - arandr
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - dex
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - eos-skel-ce-qtile
    - feh
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - lxappearance-gtk3
    - mpv
    - network-manager-applet
    - papirus-icon-theme
    - pasystray
    - picom
    - polkit-gnome
    - qtile
    - rofi
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
    - thunar-volman
    - ttf-cascadia-code
    - ttf-nerd-fonts-symbols
    - tumbler
    - xbindkeys
    - xcursor-neutral
    - xdg-user-dirs-gtk
    - xfce4-terminal
    - xorg-xbacklight
    - xorg-xdpyinfo

- name: "Sway Edition"
  description: "Sway Community Edition."
  hidden: false
  selected: false
  critical: true
  packages:
    - acpi
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - boost-libs
    - brightnessctl
    - dex
    - diffuse
    - egl-wayland
    - endeavouros-xfce4-terminal-colors
    - eos-qogir-icons
    - eos-skel-ce-sway
    - file-roller
    - grim
    - gtk-engine-murrine
    - gtk-layer-shell
    - htop
    - imv
    - jq
    - lxappearance
    - ly
    - mako
    - network-manager-applet
    - oniguruma
    - awesome-terminal-fonts
    - polkit-gnome
    - slurp
    - sway
    - swaybg
    - swayidle
    - swaylock
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-media-tags-plugin
    - thunar-volman
    - ttf-jetbrains-mono
    - ttf-nerd-fonts-symbols
    - ttf-ubuntu-font-family
    - waybar
    - wayland-protocols
    - wl-clipboard
    - wofi
    - xdg-desktop-portal-wlr
    - xed
    - xfce4-terminal
    - xorg-xhost
    - xorg-xwayland

- name: "Worm Edition"
  description: "Worm Community Edition."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme
    - dex
    - dunst
    - eos-lxdm-gtk3
    - eos-skel-ce-worm
    - feh
    - file-roller
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - papirus-icon-theme
    - picom
    - tint2
    - rofi
    - sxhkd
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - ttf-jetbrains-mono
    - ttf-nerd-fonts-symbols
    - tumbler
    - worm
    - xcursor-neutral
    - xdg-user-dirs-gtk
    - xed
    - xfce4-terminal
