#!/bin/bash

## Script to compare Community edition packages between ARM and x64

curl https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-calamares/main/calamares/modules/netinstall.yaml > x86_pkgs

curl https://raw.githubusercontent.com/endeavouros-arm/calamares-image/main/configs/calamares/modules/netinstall.yaml > aarch64_pkgs

sed -i '/- name: "XFCE4-Desktop"/,$!d' x86_pkgs

meld aarch64_pkgs x86_pkgs

rm x86_pkgs aarch64_pkgs

exit

