#!/bin/bash

curl https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-calamares/main/calamares/modules/packagechooser_ce.conf > x86_pkgs

curl https://raw.githubusercontent.com/endeavouros-arm/calamares-image/main/configs/calamares/modules/packagechooser_ce.conf > aarch64_pkgs

# sed -i '/akm\|eos-base\|paru\|zfs-dkms\|zfs-utils/d' x86_pkgs
# sed -i '/nvidia\|reflector\|ly\|grub/d' x86_pkgs
# sed -i '/keyserver-rank\|downgrade\|mkinitcpio/d' x86_pkgs
# sed -i '/virtualbox-ext-oracle\|rate-mirrors/d' x86_pkgs
# # sed -i '/calamares_current/d' x86_pkgs
# # sed -i '/calamares_config_ce\|calamares_config_default/d' x86_pkgs
# sed -i '/linux-odroid\|linux-odroid-headers\|mesa-devel-git\|odroid-alsa/d' aarch64_pkgs


meld aarch64_pkgs x86_pkgs

rm x86_pkgs aarch64_pkgs

exit

