#!/bin/bash

_base_addons() {
    pacman -U --noconfirm /home/alarm/configs/packages/*.tar.{xz,zst,gz} 2>/dev/null
}

_clean_up_script() {
    cp /root/configs/clean-up.sh /usr/local/bin/clean-up.sh
    chmod +x /usr/local/bin/clean-up.sh
    cp /root/configs/clean-up.service /etc/systemd/system/clean-up.service
}   # end of function _clean_up_script

_set_bash_alias() {
    printf "\nalias ll='ls -l --color=auto'\n" >> /etc/bash.bashrc
    printf "alias la='ls -al --color=auto'\n" >> /etc/bash.bashrc
    printf "alias lb='lsblk -o NAME,FSTYPE,FSSIZE,LABEL,MOUNTPOINT'\n\n" >> /etc/bash.bashrc
}   # end of function _set_bash_alias



_finish_up() {
    printf "alarm ALL=(ALL:ALL) NOPASSWD: ALL\n" >> /etc/sudoers
    gpasswd -a alarm wheel
    printf "export DISPLAY=':0'\nxhost +SI:localuser:alarm\nxhost +SI:localuser:root\nexec openbox-session\n" >> /home/alarm/.xinitrc
    printf "if [ -z \"\${DISPLAY}\" ] && [ \"\${XDG_VTNR}\" -eq 1 ]; then\n  exec startx\nfi\n" >> /home/alarm/.bash_profile
    chown alarm:alarm /home/alarm/.xinitrc
    chmod 644 /home/alarm/.xinitrc
    rm -rf /endeavouros*
    systemctl enable NetworkManager.service
    _set_bash_alias
    rm /var/cache/pacman/pkg/* 2>/dev/null
    rm /root/eos-arm-chroot
    rm -rf /etc/pacman.d/gnupg
    rm -rf /var/log/pacman.log
    # rm -rf /etc/lsb-release
    cp /root/configs/endeavouros-calamares-wallpaper.png /usr/share/endeavouros/backgrounds/endeavouros-calamares-wallpaper.png
    # from old config_script.sh
    rm -rf /home/alarm/.config
    mkdir /home/alarm/.config
    mkdir /home/alarm/Desktop
    # cp /boot/config.txt /boot/config.txt.orig
    # cp rpi4-config.txt /boot/config.txt
    cp /usr/lib/systemd/system/getty@.service /usr/lib/systemd/system/getty@.service.bak
    cp /root/configs/getty@.service /usr/lib/systemd/system/getty@.service
    _clean_up_script

    if [ "$TYPE" == "Image" ]; then
        cp /root/configs/resize-fs.service /etc/systemd/system/resize-fs.service
        cp /root/configs/resize-fs.sh /usr/local/bin/resize-fs.sh
        chmod +x /usr/local/bin/resize-fs.sh
        systemctl enable resize-fs.service
    fi
    cp -r /root/configs/Desktop/* /home/alarm/Desktop/
    cp -r /root/configs/.config/* /home/alarm/.config/
    rm /home/alarm/.Xauthority
    cp /root/configs/calamares/modules/* /etc/calamares/modules/
    cp /root/configs/calamares/scripts/* /etc/calamares/scripts
    cp /root/configs/calamares/settings_online.conf  /etc/calamares/
    cp /root/configs/calamares/settings_community.conf  /etc/calamares/
    chown -R alarm:alarm  /home/alarm/.config /home/alarm/Desktop
    printf "[Match]\nName=wlan*\n\n[Network]\nDHCP=yes\nDNSSEC=no\n" > /etc/systemd/network/wlan.network
    systemctl enable systemd-timesyncd
    printf "\n${CYAN}Chroot Complete${NC}\n"
}   # end of function _finish_up


######################   Start of Script   #################################
Main() {

    PLATFORM_NAME=" "

   # Declare color variables
      GREEN='\033[0;32m'
      RED='\033[0;31m'
      CYAN='\033[0;36m'
      NC='\033[0m' # No Color

   # STARTS HERE
   dmesg -n 1 # prevent low level kernel messages from appearing during the script

   # read in platformname passed by install-image-aarch64.sh
   file="/root/platformname"
   read -d $'\x04' PLATFORM_NAME < "$file"
   file="/root/type"
   read -d $'\x04' TYPE < "$file"
   sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 5/g' /etc/pacman.conf
   sed -i "s|#Color|Color\nILoveCandy|g" /etc/pacman.conf
   sed -i "s|#VerbosePkgLists|VerbosePkgLists\nDisableDownloadTimeout|g" /etc/pacman.conf
   sed -i "s|\[core\]|\[endeavouros\]\nSigLevel = PackageRequired\nInclude = /etc/pacman.d/endeavouros-mirrorlist\n\n\[core\]|g" /etc/pacman.conf
   # printf "\n[endeavouros]\nSigLevel = PackageRequired\nInclude = /etc/pacman.d/endeavouros-mirrorlist\n\n" >> /etc/pacman.conf


   useradd -p "alarm" -G users -s /bin/bash -u 1001 "alarm"
   printf "\n${CYAN}Setting root user password...${NC}\n"
   echo "alarm:alarm" | chpasswd -c SHA256
   echo "root:root" | chpasswd -c SHA256
   printf "\n${CYAN}Root user password set...${NC}\n\n"
   cp -r /root/configs/ /home/alarm/

   case $PLATFORM_NAME in
     rpi) cp /boot/config.txt /boot/config.txt.orig
          cp /root/configs/rpi4-config.txt /boot/config.txt
          ;;
     pbp) sed -i 's|^MODULES=(|MODULES=(btrfs |' /etc/mkinitcpio.conf
          ;;
     rad) # cp -r /root/extlinux /boot
          mkinitcpio -P
          ;;
   esac

#   _base_addons

   _finish_up
   chown -R alarm:alarm /home/alarm
}  # end of Main

Main "$@"
