#!/bin/bash

_partition_Pinebook() {
    dd if=/dev/zero of=$DEVICENAME bs=1M count=16
    parted --script -a minimal $DEVICENAME \
    mklabel msdos \
    unit mib \
    mkpart primary fat32 16MiB 216MiB \
    mkpart primary 216MiB $DEVICESIZE"MiB" \
    quit
}

_partition_OdroidN2() {
    parted --script -a minimal $DEVICENAME \
    mklabel msdos \
    unit mib \
    mkpart primary fat32 2MiB 258MiB \
    mkpart primary 258MiB $DEVICESIZE"MiB" \
    quit
}

_partition_RPi4() {
    parted --script -a minimal $DEVICENAME \
    mklabel gpt \
    unit MiB \
    mkpart primary fat32 2MiB 202MiB \
    mkpart primary ext4 202MiB $DEVICESIZE"MiB" \
    quit
}

_install_Pinebook_image() {
    case $ARCH in
        aarch64)
            pacstrap -cGM MP - < $(pwd)/build-configs/pkglist-pbp.txt
            ;;
        x86_64)
            pacstrap -GMC $(pwd)/build-configs/eos-pacman.conf  MP - < $(pwd)/build-configs/pkglist-pbp.txt
            ;;
    esac
    _copy_stuff_for_chroot
    genfstab -L MP >> MP/etc/fstab
}   # End of function _install_Pinebook_image

_install_OdroidN2_image() {
    case $ARCH in
        aarch64)
            pacstrap -cGM MP - < $(pwd)/build-configs/pkglist-odn.txt
            ;;
        x86_64)
            pacstrap -GMC $(pwd)/build-configs/eos-pacman.conf  MP - < $(pwd)/build-configs/pkglist-odn.txt
            ;;
    esac
    _copy_stuff_for_chroot
    genfstab -L MP >> MP/etc/fstab
}   # End of function _install_OdroidN2_image


_install_RPi4_image() { 
    case $ARCH in
        aarch64)
            pacstrap -cGM MP - < $(pwd)/build-configs/pkglist-rpi.txt
            ;;
        x86_64)
            ln -s $(pwd)/build-configs/mirrorlist /etc/pacman.d/arch-mirrorlist
            ln -s $(pwd)/build-configs/eos-mirrorlist /etc/pacman.d/eos-mirrorlist
            pacstrap -GMC $(pwd)/build-configs/eos-pacman.conf  MP - < $(pwd)/build-configs/pkglist-rpi.txt
            rm /etc/pacman.d/arch-mirrorlist
            rm /etc/pacman.d/eos-mirrorlist
            ;;
    esac
    _copy_stuff_for_chroot
    # sed -i 's/mmcblk0/mmcblk1/' MP/etc/fstab
    genfstab -L MP >> MP/etc/fstab
    old=$(awk '{print $1}' MP/boot/cmdline.txt)
    new="root=LABEL=ROOT_EOS"
    boot_options=" usbhid.mousepoll=8"
    sed -i "s#$old#$new#" MP/boot/cmdline.txt
    sed -i "s/$/$boot_options/" MP/boot/cmdline.txt
}  # End of function _install_RPi4_image

_partition_format_mount() {
   # truncate -s 6G test.img
   fallocate -l 7.5G test.img
   fallocate -d test.img
   # dd if=/dev/zero of=./test.img bs=4MiB count=1500 conv=sparse,sync,noerror
   # dd conv=sparse bs=1MiB count=6000 if=/dev/zero of=./test.img
   # losetup --find --show test.img | read DVN
   DVN=$(losetup --find --show test.img)
   DEVICENAME="$DVN"
   printf "\n${CYAN} DEVICENAME ${NC}\n"
   echo $DEVICENAME
   echo $DVN
   # DEVICENAME="/dev/loop0"
   ##### Determine data device size in MiB and partition ###
   printf "\n${CYAN}Partitioning, & formatting storage device...${NC}\n"
   DEVICESIZE=$(fdisk -l | grep "Disk $DEVICENAME" | awk '{print $5}')
   ((DEVICESIZE=$DEVICESIZE/1048576))
   ((DEVICESIZE=$DEVICESIZE-10))  # for some reason, necessary for USB thumb drives
   printf "\n${CYAN}Partitioning storage device $DEVICENAME...${NC}\n"
   printf "\ndevicename = $DEVICENAME     devicesize = $DEVICESIZE\n" >> /root/enosARM.log
   # umount partitions before partitioning and formatting
   case $PLATFORM in   
      RPi64)    _partition_RPi4 ;;
      OdroidN2) _partition_OdroidN2 ;;
      Pinebook) _partition_Pinebook ;;
   esac
  
   printf "\npartition name = $DEVICENAME\n\n" >> /root/enosARM.log
   printf "\n${CYAN}Formatting storage device $DEVICENAME...${NC}\n"
   printf "\n${CYAN}If \"/dev/sdx contains a ext4 file system Labelled XXXX\" or similar appears, Enter: y${NC}\n\n\n"

   DEVICENAME1=$DEVICENAME"p"
   
   PARTNAME1=$DEVICENAME1"1"
   mkfs.fat -n BOOT_EOS $PARTNAME1   2>> /root/enosARM.log
   PARTNAME2=$DEVICENAME1"2"
   mkfs.ext4 -F -L ROOT_EOS $PARTNAME2   2>> /root/enosARM.log
   # mkdir MP1 MP
   mkdir MP
   mount $PARTNAME2 MP
   mkdir MP/boot
   mount $PARTNAME1 MP/boot
   if [ "$ARCH" == "x86_64" ]; then
       mkdir -p MP/usr/bin
       cp /usr/bin/qemu-aarch64-static MP/usr/bin
   fi

} # end of function _partition_format_mount

_check_if_root() {
    local whiptail_installed

    if [ $(id -u) -ne 0 ]
    then
       whiptail_installed=$(pacman -Qs libnewt)
       if [[ "$whiptail_installed" != "" ]]; then
          whiptail --title "Error - Cannot Continue" --msgbox "  Please run this script as sudo or root" 8 47
          exit
       else
          printf "${RED}Error - Cannot Continue. Please run this script as sudo or root.${NC}\n"
          exit
       fi
    fi
    if [[ "$SUDO_USER" == "" ]]; then     
         USERNAME=$USER
    else
         USERNAME=$SUDO_USER  
    fi
}  # end of function _check_if_root

_copy_stuff_for_chroot() {
    cp eos-arm-chroot MP/root/
    cp config_script.sh MP/root/
    mkdir -p MP/root/
    cp -r configs/ MP/root/
    printf "$PLAT\n" > platformname
    cp platformname MP/root/
    rm platformname
    printf "$TYPE\n" > type
    cp type MP/root/
    rm type
}

_arch_chroot(){
    arch-chroot MP /root/eos-arm-chroot
    # arch-chroot MP /root/config_script.sh
}

_create_image(){
    case $PLATFORM in
       OdroidN2)# time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-odroid-n2-latest.tar.zst *
          zstd -z --sparse --rsyncable -10 -T0 test.img -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-odroid-n2-latest.img.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-odroid-n2-latest.img.zst > enosLinuxARM-odroid-n2-latest.img.zst.sha512sum
          cd $dir ;;
       Pinebook)# time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-pbp-latest.tar.zst *
          zstd -z --sparse --rsyncable -10 -T0 test.img -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-pbp-latest.img.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-pbp-latest.img.zst > enosLinuxARM-pbp-latest.img.zst.sha512sum
          cd $dir ;;
       RPi64) # time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-rpi-aarch64-latest.tar.zst *
          zstd -z --sparse --rsyncable -10 -T0 test.img -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-rpi-aarch64-latest.img.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-rpi-aarch64-latest.img.zst > enosLinuxARM-rpi-aarch64-latest.img.zst.sha512sum
          cd $dir ;;
    esac
}

_create_rootfs(){
    case $PLATFORM in
       OdroidN2)# time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-odroid-n2-latest.tar.zst *
          time bsdtar -cf - * | zstd -z --rsyncable -10 -T0 -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-odroid-n2-latest.tar.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          cd ..
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-odroid-n2-latest.tar.zst > enosLinuxARM-odroid-n2-latest.tar.zst.sha512sum
          cd $dir ;;
       Pinebook)# time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-pbp-latest.tar.zst *
          time bsdtar -cf - * | zstd -z --rsyncable -10 -T0 -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-pbp-latest.tar.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          cd ..
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-pbp-latest.tar.zst > enosLinuxARM-pbp-latest.tar.zst.sha512sum
          cd $dir ;;
       RPi64) # time bsdtar --use-compress-program=zstdmt -cf /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-rpi-aarch64-latest.tar.zst *
          time bsdtar -cf - * | zstd -z --rsyncable -10 -T0 -of /home/$USERNAME/endeavouros-arm/test-images/enosLinuxARM-rpi-aarch64-latest.tar.zst
          printf "\n\nbsdtar is finished creating the image.\nand will calculate a sha512sum\n\n"
          cd ..
          dir=$(pwd)
          cd /home/$USERNAME/endeavouros-arm/test-images/
          sha512sum enosLinuxARM-rpi-aarch64-latest.tar.zst > enosLinuxARM-rpi-aarch64-latest.tar.zst.sha512sum
          cd $dir ;;
    esac
}

_help() {
   # Display Help
   printf "\nHELP\n"
   printf "Build EndeavourOS ARM Images\n"
   printf "options:\n"
   printf " -h  Print this Help.\n\n"
   printf "All these options are required\n"
   printf " -p  enter platform: rpi or odn or pbp\n"
   printf " -t  image type: r (for rootfs) or i (for image) \n"
   printf " -c  create image: y or n\n"
   printf "example: sudo ./eos-arm-build -p rpi -t i -c y \n\n"
}

_read_options() {
    # Available options
    opt=":p:t:c:h:"
    local OPTIND

    if [[ ! $@ =~ ^\-.+ ]]
    then
      echo "The script requires an argument, aborting"
      _help
      exit 1
    fi

    while getopts "${opt}" arg; do
      case $arg in
        p)
          PLAT="${OPTARG}"
          ;;
        t)
          TYP="${OPTARG}"
          ;;
        c)
          CRE="${OPTARG}"
          ;;
        \?)
          echo "Option -${OPTARG} is not valid, aborting"
          _help
          exit 1
          ;;
        h|?)
          _help
          exit 1
          ;;
        :)
          echo "Option -${OPTARG} requires an argument, aborting"
          _help
          exit 1
          ;;
      esac
    done
    shift $((OPTIND-1))

    case $PLAT in
         rpi) PLATFORM="RPi64" ;;
         odn) PLATFORM="OdroidN2" ;;
         pbp) PLATFORM="Pinebook" ;;
           *) PLAT1=true;;
    esac

    case $CRE in
         y) CREATE=true ;;
         n) CREATE=false ;;
         *) CREATE=true ;;
    esac

    case $TYP in
         r) TYPE="Rootfs" ;;
         i) TYPE="Image" ;;
         *) TYPE=" " ;;
    esac


}

#################################################
# beginning of script
#################################################

Main() {
    # VARIABLES
    PLAT=""
    PLATFORM=" "     # e.g. OdroidN2, RPi4b, etc.
    DEVICENAME=" "   # storage device name e.g. /dev/sda
    DEVICESIZE="1"
    PARTNAME1=" "
    PARTNAME2=" "
    USERNAME=" "
    CRE=" "
    CREATE=" "
    TYP=" "
    TYPE=" "
    ARCH="$(uname -m)"
    
    # Declare color variables
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    CYAN='\033[0;36m'
    NC='\033[0m' # No Color

    pacman -S --noconfirm --needed libnewt arch-install-scripts time &>/dev/null # for whiplash dialog
    _check_if_root
    _read_options "$@"

    rm -rf test.img
    _partition_format_mount  # function to partition, format, and mount a uSD card or eMMC card
    case $PLATFORM in
       RPi64)    _install_RPi4_image ;;
       OdroidN2) _install_OdroidN2_image ;;
       Pinebook) _install_Pinebook_image ;;
    esac

    printf "\n\n${CYAN}arch-chroot to switch kernel.${NC}\n\n"
    _arch_chroot
    
    if [ "$ARCH" == "x86_64" ]; then
       rm MP/usr/bin/qemu-aarch64-static
    fi

    case $PLATFORM in
       OdroidN2)
          dd if=MP/boot/u-boot.bin of=$DEVICENAME conv=fsync,notrunc bs=512 seek=1
          ;;
       Pinebook)
           sed -i "s|root=LABEL=ROOT_ALARM|root=/dev/mmcblk1p2|g" MP/boot/extlinux/extlinux.conf
           # u-boot
           # dd if=MP/boot/idbloader.img of=$DEVICENAME seek=64 conv=notrunc,fsync
           # dd if=MP/boot/u-boot.itb of=$DEVICENAME seek=16384 conv=notrunc,fsync
           # Tow-Boot
           dd if=MP/boot/Tow-Boot.noenv.bin of=$DEVICENAME seek=64 conv=notrunc,fsync
           ;;
    esac
    
    if $CREATE ; then

        if [ "$TYPE" == "Rootfs" ]; then
            printf "\n\n${CYAN}Creating Rootfs${NC}\n\n"
            cd MP
            _create_rootfs
            printf "\n\n${CYAN}Created Rootfs${NC}\n\n"
        fi
    fi

    umount MP/boot MP
    rm -rf MP

    losetup -d /dev/loop0
    # rm ArchLinuxARM*
    if $CREATE ; then
        if [ "$TYPE" == "Image" ]; then
            printf "\n\n${CYAN}Creating Image${NC}\n\n"
            _create_image
            printf "\n\n${CYAN}Created Image${NC}\n\n"
        fi
    fi

    exit
}

Main "$@"
